# Use an official Node.js runtime as a parent image
FROM node:12-alpine as build

# Set the working directory to /app
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the remaining project files to the container
COPY . .

# Build the app for production with npm
RUN npm run build

# Use an official Nginx runtime as a parent image
FROM nginx:alpine

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy our Nginx configuration file to the container
COPY nginx.conf /etc/nginx/conf.d

# Copy the built React app files from the build stage to the Nginx web root
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80
EXPOSE 80
# Start Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
