version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    restart: always
    networks:
      - internal

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    restart: always
    environment:
      - PORT=${PORT}
      - COUCHDB_URL=${COUCHDB_URL}
      - REDIS_URL=${REDIS_URL}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
    depends_on:
      - couchdb
      - redis
    networks:
      - internal
  
  couchdb:
    image: couchdb:latest
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - /home/couchdb/data:/opt/couchdb/data:rw
      - ./couchdb_init_scripts/couchdb_setup.sh:/usr/local/bin/couchdb_setup.sh
    networks:
      - internal
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    entrypoint: redis-server --appendonly yes
    restart: always
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  redis-data:
    driver: local
    
  